### ISSUE TITLE
Uncaught AttributeError: Connector instance has no attribute 'iface'


### ISSUE THREAD

**Issue by peter-shr** [HabeltWi/AutoForm#2]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/>user</.qgis2/python/plugins\AutoForm\autoform.py", line 62, in handleFormofLayer
    self.identifyRelations(selected_layer)
  File "C:/Users/>user</.qgis2/python/plugins\AutoForm\autoform.py", line 116, in identifyRelations
    cur = self.connector.uriDatabaseConnect(uri)
  File "C:/Users/>user</.qgis2/python/plugins\AutoForm\connector.py", line 32, in uriDatabaseConnect
    QMessageBox.warning(self.iface.mainWindow(), "Connection Error", "Failed to connect to database. Please make sure that your connection information is correct.")
AttributeError: Connector instance has no attribute 'iface'

```
AutoForm 0.1.0, QGIS 2.14.11-Essen on Windows 8

**Comment by HabeltWi** [comment]
Hello peter-shr

Try using the newer version of the plugin. I believe I've fixed the problem now.
